# Global project configuration 

# Paths
DATA_RAW_DIR = "data/raw"
DATA_OUTPUT_DIR = "data/output"

# LLM defaults
LLM_DEFAULT_MODEL = "llama-3.3-70b-versatile"
LLM_TEMPERATURE = 0.0
LLM_MAX_RETRIES = 3
LLM_RETRY_DELAY_SECONDS = 5

# Embedding
EMBEDDING_MODEL = "nomic-ai/nomic-embed-text-v1.5"
EMBEDDING_TRUST_REMOTE_CODE = True
EMBEDDING_NORMALIZE = True

# Chunking
CHUNK_TARGET_TOKENS = 400
CHUNK_MAX_TOKENS = 550
CHUNK_MIN_TOKENS = 50

# Per-step model selection
EXTRACTOR_MODEL = LLM_DEFAULT_MODEL
ENTITY_RESOLUTION_MODEL = LLM_DEFAULT_MODEL
RELATION_DEFINITION_MODEL = LLM_DEFAULT_MODEL
RELATION_CANONICALIZATION_MODEL = LLM_DEFAULT_MODEL
RELATION_SINGLETON_NORMALIZATION_MODEL = LLM_DEFAULT_MODEL
ENTITY_CONCEPT_MODEL = LLM_DEFAULT_MODEL
RELATION_CONCEPT_MODEL = LLM_DEFAULT_MODEL

# Pipeline parameters
ENTITY_SIMILARITY_THRESHOLD = 0.7
ENTITY_TOP_K_CANDIDATES = 5
ENTITY_MAX_CONTEXT_TRIPLES = 3

RELATION_SIMILARITY_THRESHOLD = 0.7
RELATION_TOP_K_CANDIDATES = 5
RELATION_SINGLETON_BATCH_SIZE = 10

RELATION_DEFINITION_BATCH_SIZE = 10
SCHEMA_BATCH_SIZE = 8
